### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maxxonair** [maxxonair/inventory#1]
Development Todo list

UI:

- [ ]  Home tab | Make change item image function in a hidden view (enable  via button)
- [ ] All tabs | make scan button less
- [ ] Login needs to show error messages

Advanced:

- [ ] Add function to create and maintain users
- [ ] Add database export function
- [ ]

**Comment by maxxonair** [comment]
Closing as it's obsolete
